analysis_electrodes: '14 '
analysis_settings:
  '1':
    label: VisStart
    event: Trial Onset
    time:
    - 0
    - 0.5
    frequency_dd: Select one
    frequency:
    - 70
    - 150
baseline_settings:
  window:
  - - -1.0
    - -0.5
  scope: Per frequency, trial, and electrode
  unit_of_analysis: '% Change Power'
condition_variable: Condition
custom_roi_groupings:
  '1':
    label: ''
    conditions: []
custom_roi_type: Filter only
custom_roi_variable: none
electrode_export_data_type: tensor
electrode_export_file_type: HDF5
electrodes_to_export: ''
electrodes_to_export_roi_categories: ~
electrodes_to_export_roi_name: none
enable_custom_ROI: no
enable_second_condition_groupings: no
epoch_choice: auditory_onset
epoch_choice__trial_ends: 2
epoch_choice__trial_ends_rel_to_event: Trial Onset
epoch_choice__trial_starts: -1
epoch_choice__trial_starts_rel_to_event: Trial Onset
first_condition_groupings:
  '1':
    label: audio_visual
    conditions:
    - known_av
    - meant_av
    - last_av
    - drive_av
  '2':
    label: auditory_only
    conditions:
    - last_a
    - drive_a
    - known_a
    - meant_a
  '3':
    label: visual_only
    conditions:
    - last_v
    - drive_v
    - known_v
    - meant_v
frequencies_to_export: Collapsed, Analysis window(s) only
loaded_electrodes: 13-16,24
omnibus_includes_all_electrodes: yes
project_name: demo
reference_name: default
second_condition_groupings:
  '1':
    label: ML
    conditions: []
  '2':
    label: VL
    conditions: []
subject_code: DemoSubject
time_censor:
  enabled: no
  window:
  - 0.0
  - 1.0
times_to_export: Raw, All available times
trial_outliers_list: ~
trials_to_export: Raw, Only trials used in grouping factors
